### ISSUE TITLE
Version number log update

### ISSUE THREAD

**Issue by azey** [Orange-OpenSource/OCast-iOS#6]
https://github.com/Orange-OpenSource/OCast-iOS/blob/bc011cc913fce90c64e6131ae17bebae685dd0ea/OCast/Classes/Core/Device/DeviceDiscovery.swift#L142

Shouldn't the version number be updated?

**Comment by chazemar** [comment]
Hi,

This info is obsolete. The version can be found in OCast.podspec

Regards,
