### ISSUE TITLE
 device.connect() - no success, no error

### ISSUE THREAD

**Issue by LeDanielH** [Orange-OpenSource/OCast-iOS#81]
**Describe the bug**
Nothing happens when calling `device?.connect(oldSSLConfig)` right after it failed with `device?.connect(regularSSLConfig)`. Adding delay to the second call (with `oldSSLConfig`) "fixed" the issue.

**To reproduce**
```swift
    func connectWithOldCert(completion: @escaping (Bool) -> Void) {
        let callDelay = 2.0

        DispatchQueue.main.asyncAfter(deadline: .now() + callDelay) {

            // WHEN CALLED IMMEDIATELY, NOTHING HAPPENS, NO SUCCESS, NO ERROR 
            self.initDevice(useOldCert: true, completion: completion)
        }
    }

    func initDevice(useOldCert: Bool, completion: @escaping (Bool) -> Void) {
        let sslConfig = getSSLConfiguration(useOldCert: useOldCert)

        device?.connect(sslConfig) { [weak self] error in

            // NO LOGS ARE VISIBLE HERE when `device?.connect(oldSSLConfig)` IS CALLED WITHOUT TIMEOUT

            if let error = error {
                if useOldCert == false {
                    print("Ocast:Failed to initialize device with new cert. Trying failover to old cert...")
                    self?.connectWithOldCert(completion: completion)
                } else {
                    print("Ocast:device init failed with \(error.localizedDescription)")
                    self?.handleInitDeviceFailed(completion: completion)
                }
            } else {
                print("Ocast:device init for \(self?.device?.friendlyName ?? "missing stick name") success")
                completion(true)
            }
        }
    }
```
1. I try to pair IPhone with a stick, that requires an `oldSSLConfig`
2. I call `initDevice()` with `useOldCert = false` first
3. `useOldCert` is used to retrieve `sslConfig` from `getSSLConfiguration`
4. if `device?.connect()` fails with the retrieved `sslConfig`, I again call `initDevice()` with `useOldCert: true`  (via `connectWithOldCert`)
5. `device?.connect()` does not throw error or success
6. adding delay to this second call "fixes" the issue

**Expected behavior**
+ Ideally - It does not fail when calling `device?.connect(oldSSLConfig)` right after it failed with`regularSSLConfig` 
+ Or at least - I get an error on why it failed the second time from OCast pod package

**Smartphone (please complete the following information):**
- XCode - 11.3.1
- 'OCast', '2.0.1'
- Any emulator IOS 13.3

**Additional context**
I did some digging. When  `device?.connect(oldSSLConfig)` was called,  nothing failed all the way to `createHTTPRequest` inside `Pods > Starscream > WebSocket.swift`. I stopped there.

**Comment by fsuc** [comment]
Hello,

I can't test with an expired certificate but the following code works on Xcode 11.6 : 

```
    private func connect(completion: @escaping (Bool) -> Void) {
        let sslConfiguration = self.sslConfiguration(fail: true)
        device.connect(sslConfiguration) { [weak self] error in
            guard let `self` = self else { return }
            print("FIRST CONNECT CALLBACK \(String(describing: error?.localizedDescription))")
            if error != nil {
                let sslConfiguration = self.sslConfiguration(fail: false)
                self.device.connect(sslConfiguration) { error in
                    print("SECOND CONNECT CALLBACK \(String(describing: error?.localizedDescription))")
                    completion(error == nil)
                }
            } else {
                completion(true)
            }
        }
    }
```

If the fail parameter is true, the server certificate is not set in the configuration. 
Here's the output :
FIRST CONNECT CALLBACK Optional("The operation couldn’t be completed. (OCast.OCastError error 20.)")
SECOND CONNECT CALLBACK nil
